Health-Education-England/tis-trainee-notifications

- .aws/task-definition-template.json
- build.gradle
- src/main/java/uk/nhs/tis/trainee/notifications/dto/FormUpdateEvent.java
- src/main/java/uk/nhs/tis/trainee/notifications/event/FormListener.java
- src/main/resources/application.yml
- src/main/resources/templates/email/form-updated.html
- src/test/java/uk/nhs/tis/trainee/notifications/event/FormListenerIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/FormListenerTest.java
> Feat: form notifications

- .aws/task-definition-template.json
- build.gradle
- src/main/java/uk/nhs/tis/trainee/notifications/dto/CredentialEvent.java
- src/main/java/uk/nhs/tis/trainee/notifications/event/CredentialListener.java
- src/main/resources/application.yml
- src/main/resources/templates/email/credential-revoked.html
- src/test/java/uk/nhs/tis/trainee/notifications/event/CredentialListenerIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/CredentialListenerTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
Send a notification email when a credential is revoked.
TIS21-5115
TIS21-5134
> feat: send email notification for revoked creds

- build.gradle
- src/main/resources/application.yml
- src/test/java/uk/nhs/tis/trainee/notifications/repository/FlywayMigrationsTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceIntegrationTest.java
- src/test/resources/application-mysql.yml
- src/test/resources/application-test.yml
- src/test/resources/bootstrap.properties
> fix: create schema if does not exist

- .aws/task-definition-template.json
- build.gradle
Dependent on https://github.com/Health-Education-England/TIS-OPS/pull/712
NO-TICKET
> fix: get PM queue env var from parameter store

- build.gradle
- src/main/java/uk/nhs/tis/trainee/notifications/dto/HistoryDto.java
- src/main/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapper.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/History.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/TisReferenceType.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java
- src/test/java/uk/nhs/tis/trainee/notifications/api/HistoryResourceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java
Extend the History class to incorporate TIS reference info to record the entity type and Id.
Convo: https://hee-nhs-tis.slack.com/archives/C03G3UK3U82/p1699955293415679?thread_ts=1699632870.154349&cid=C03G3UK3U82
TIS21-5083
> Feat: history TIS reference info

- build.gradle
- src/main/java/uk/nhs/tis/trainee/notifications/event/ProgrammeMembershipListener.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/ProgrammeMembershipListenerTest.java
> fix: handle PM deletes which do not have recrd content

- build.gradle
- src/main/resources/application.yml
> fix: disable mongock transations

- build.gradle
- src/main/java/uk/nhs/tis/trainee/notifications/migration/DeleteUnusedPmUpdateHistory.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java
- src/test/java/uk/nhs/tis/trainee/notifications/migration/DeleteUnusedPmUpdateHistoryTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
And purge obsolete history records.
TIS21-5387
> fix: history recipient fix

- build.gradle
- src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
Refactor to use EmailService.sendMessage instead of custom NotificationService handling.
TIS21-5389
> fix: use EmailService for notifications

- build.gradle.kts
> chore: dependabot rollup inc SpringCloud2023

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/migration/DeleteUnusedPmUpdateHistory.java
No tests though :/
FWIW it seems to work locally 🙈 
NO-TICKET
> fix: always run mongock DeleteUnusedPmUpdateHistory

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/dto/HistoryDto.java
- src/main/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapper.java
- src/test/java/uk/nhs/tis/trainee/notifications/api/HistoryResourceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/api/TraineeHistoryResourceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapperTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
> fix: add subjectText to history DTO

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java
Should not exist, but some legacy data is missing placement type.
NO-TICKET
> fix: handle empty placement type

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/event/UserAccountListener.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/InAppService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java
- src/main/resources/application.yml
- src/main/resources/templates/in-app/e-portfolio/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/event/UserAccountListenerTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/InAppServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
The e-portfolio notification should be used for new starters taking part
in the pilot.
It will only be created, as an in-app notification if it has not been
created before.
TIS21-5615
> feat: create ePortfolio notification

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/service/MessagingControllerService.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/MessagingControllerServiceTest.java
> fix: putting the whitelist logic back to isValidRecipient() for the use of in-app notification

- .aws/task-definition-template.json
- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/dto/ContactDetailsEvent.java
- src/main/java/uk/nhs/tis/trainee/notifications/event/ContactDetailsListener.java
- src/main/java/uk/nhs/tis/trainee/notifications/mapper/ContactDetailsMapper.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/ContactDetails.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/History.java
- src/main/java/uk/nhs/tis/trainee/notifications/repository/HistoryRepository.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/ContactDetailsService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/InAppService.java
- src/main/resources/application.yml
- src/main/resources/templates/email/coj-confirmation/v1.0.0.html
- src/main/resources/templates/email/credential-revoked/v1.0.0.html
- src/main/resources/templates/email/form-updated/v1.0.0.html
- src/main/resources/templates/email/placement-updated-week-12/v1.0.0.html
- src/main/resources/templates/email/programme-created/v1.0.0.html
- src/main/resources/templates/fragments/retry/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/event/ContactDetailsListenerTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapperTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/migration/PopulateNotificationHistoryStatusIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/ContactDetailsServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java
Dependent on https://github.com/Health-Education-England/TIS-OPS/pull/775
TIS21-5746
TIS21-5747
TIS21-5745
> feat: resent failed emails

- build.gradle.kts
- src/main/resources/templates/email/placement-updated-week-12/v1.0.0.html
- src/main/resources/templates/email/programme-created/v1.0.0.html
> fix: use full URL paths for images

- build.gradle.kts
- src/main/resources/templates/in-app/deferral/v1.0.0.html
- src/main/resources/templates/in-app/e-portfolio/v1.0.0.html
- src/main/resources/templates/in-app/less-than-full-time/v1.0.0.html
- src/main/resources/templates/in-app/sponsorship/v1.0.0.html
To be work with FE change: https://github.com/Health-Education-England/tis-trainee-ui/pull/1034
This PR need to go first
<NO_TICKET>
> fix: link target to new tab for in-app notifications

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
> feat: dont schedule PM notifications, just process immediately.

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java
- src/main/resources/templates/email/placement-updated-week-12/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
Also ability to do A/B segmenting on surveys.
TIS21-5982
TIS21-5983
> fix: placement email changes

- build.gradle.kts
- src/main/resources/templates/email/placement-updated-week-12/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
As per
https://hee-nhs-tis.slack.com/archives/C03G3UK3U82/p1714736741902579
NO-TICKET
> fix: further placement email tweaks

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/api/TraineeHistoryResource.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java
- src/main/java/uk/nhs/tis/trainee/notifications/repository/HistoryRepository.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/InAppService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java
- src/main/resources/application.yml
- src/main/resources/templates/in-app/placement-information/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/api/TraineeHistoryResourceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/InAppServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java
Sample placement in-app notification
TIS21-5562
TIS21-5841
> feat: placement information in-app notification

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java
- src/main/resources/application.yml
- src/main/resources/templates/in-app/placement-useful-information/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java
> feat: Placement Useful Information notification

- build.gradle.kts
- src/main/resources/templates/email/email-updated-new/v1.0.0.html
- src/main/resources/templates/email/email-updated-old/v1.0.0.html
> fix: update email update wording for local office

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
> feat: programme deferral notifications

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/event/PlacementListener.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/PlacementListenerTest.java
> fix: delete scheduled in-app notification when placement is deleted

- src/main/resources/templates/email/coj-confirmation/v1.0.0.html
- src/main/resources/templates/email/credential-revoked/v1.0.0.html
- src/main/resources/templates/email/form-updated/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/CredentialListenerIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/FormListenerIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
> refactor: add disclaimers and logos to emails

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/migration/BroadcastNotificationHistory.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/History.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/EventBroadcastService.java
- src/test/java/uk/nhs/tis/trainee/notifications/config/MongoConfigurationIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapperTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/migration/BroadcastNotificationHistoryTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/migration/PopulateNotificationHistoryStatusIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java
Dependent on https://github.com/Health-Education-England/tis-trainee-ndw-exporter/pull/110
TIS21-6086
> feat: migrate notifications history

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java
- src/main/resources/templates/email/programme-day-one/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
With registered account:
No registered account:
TIS21-5823
TIS21-5960
TIS21-6204
TIS21-5959
> feat: email notification for Programme Day One

- build.gradle.kts
- src/main/resources/templates/email/programme-day-one/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
Note: template version has not been bumped. It felt like too minor a change to issue a new version, but this could be wrong.
TIS21-6352
TIS21-6353
TIS21-6351
> chore: update programme Day One email text

- build.gradle.kts
- src/main/resources/application.yml
> fix: set correct Sentry environment

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
Just to make it easier to test previous PR.
NO-TICKET
> fix: add logging of email-send logic

- build.gradle.kts
- src/main/resources/templates/email/placement-rollout-2024-correction/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
> fix: amend rollout correction email wording

- .aws/task-definition-template.json
- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/event/GmcListener.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/GmcDetails.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/GmcUpdateEvent.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/LocalOffice.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/LocalOfficeContact.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/LocalOfficeContactType.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/MessagingControllerService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/main/resources/application.yml
- src/main/resources/templates/email/gmc-updated/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/event/GmcListenerTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/MessagingControllerServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
> feat: handle GMC updates

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/main/resources/templates/email/gmc-updated/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
> fix: local office contact call handling

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/migration/UpdateInAppTvContact.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/test/java/uk/nhs/tis/trainee/notifications/migration/UpdateInAppTvTest.java
> fix: update Thames Valley contacts for all UNREAD in-app notifications.

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java
TIS21-6800
TIS21-6804
TIS21-6801
TIS21-6803
> fix: remove scheduled orphan from DB

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/migration/DeleteOrphanScheduledHistory.java
- src/test/java/uk/nhs/tis/trainee/notifications/migration/DeleteOrphanScheduledHistoryTest.java
> fix: Bulk delete past SCHEDULED histories

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/event/GmcListener.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/GmcListenerTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
I had a feeling set order was indeterminate, but local tests kept working with the naive assumption... :/
NO-TICKET
> fix: broken test

- build.gradle.kts
- src/main/resources/application.yml
- src/main/resources/templates/email/placement-updated-week-12/v1.2.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
> fix: amend placement email text

- build.gradle.kts
- src/main/resources/templates/email/coj-confirmation/v1.1.0.html
- src/main/resources/templates/email/credential-revoked/v1.0.0.html
- src/main/resources/templates/email/email-updated-new/v1.0.0.html
- src/main/resources/templates/email/email-updated-old/v1.0.0.html
- src/main/resources/templates/email/form-updated/v1.0.0.html
- src/main/resources/templates/email/gmc-rejected-lo/v1.0.0.html
- src/main/resources/templates/email/gmc-rejected-trainee/v1.0.0.html
- src/main/resources/templates/email/gmc-updated/v1.0.0.html
- src/main/resources/templates/email/placement-rollout-2024-correction/v1.0.0.html
- src/main/resources/templates/email/placement-updated-week-12/v1.2.0.html
- src/main/resources/templates/email/programme-created/v1.2.0.html
- src/main/resources/templates/email/programme-day-one/v1.1.0.html
> refactor: decrease logo size

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/dto/UserDetails.java
- src/main/java/uk/nhs/tis/trainee/notifications/event/EmailListener.java
- src/main/java/uk/nhs/tis/trainee/notifications/event/GmcListener.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/EventBroadcastService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java
- src/main/java/uk/nhs/tis/trainee/notifications/service/UserAccountService.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/GmcListenerTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/PlacementListenerTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceTest.java
Not currently extended to solidify our whitelisting approach, since that feels like it might need to be a separate ticket, but I am persuadable...
TIS21-6950
> fix: dont email LOs for dummy trainees

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/dto/LtftUpdateEvent.java
- src/main/java/uk/nhs/tis/trainee/notifications/dto/ProgrammeMembershipDto.java
- src/main/resources/templates/email/ltft-approved/v1.0.0.html
- src/main/resources/templates/email/ltft-submitted/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/event/LtftListenerIntegrationTest.java
- src/test/resources/email/ltft-approved-full-email-contacts.html
- src/test/resources/email/ltft-approved-full-url-contacts.html
- src/test/resources/email/ltft-approved-minimal.html
- src/test/resources/email/ltft-submitted-full-email-contacts.html
- src/test/resources/email/ltft-submitted-full-url-contacts.html
- src/test/resources/email/ltft-submitted-minimal.html
Update the submitted notification
- Remove doubled "NHS England" in subject
- Reword outcome of withdrawing an application
Update the approved notification
- Remove "TPD has been notified"
- Fix start and end dates
TIS21-6596
TIS21-6594
> fix(ltft): submitted and approved notifications

- build.gradle.kts
- src/main/resources/templates/email/ltft-submitted/v1.0.0.html
> fix(ltft): extra hyphen in LTFT submitted subject

- build.gradle.kts
- src/main/resources/templates/email/ltft-submitted-tpd/v1.0.0.html
- src/test/resources/email/ltft-submitted-tpd-full-email-contacts.html
- src/test/resources/email/ltft-submitted-tpd-full-url-contacts.html
- src/test/resources/email/ltft-submitted-tpd-minimal.html
From https://hee-nhs-tis.slack.com/archives/C03G3UK3U82/p1746625081131589 
NO-TICKET
> fix: LTFT submitted TPD email tweak

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/dto/LtftUpdateEvent.java
- src/main/java/uk/nhs/tis/trainee/notifications/event/LtftListener.java
- src/main/java/uk/nhs/tis/trainee/notifications/mapper/LtftEventMapper.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java
- src/main/resources/application.yml
- src/main/resources/templates/email/ltft-unsubmitted/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/event/LtftListenerIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/LtftListenerTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/mapper/LtftEventMapperTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
- src/test/resources/email/ltft-unsubmitted-full-email-contacts.html
- src/test/resources/email/ltft-unsubmitted-full-url-contacts.html
- src/test/resources/email/ltft-unsubmitted-minimal.html
> feat: LTFT unsubmit trainee email notification

- build.gradle.kts
- src/main/java/uk/nhs/tis/trainee/notifications/dto/LtftUpdateEvent.java
- src/main/java/uk/nhs/tis/trainee/notifications/event/LtftListener.java
- src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java
- src/main/resources/application.yml
- src/main/resources/templates/email/ltft-withdrawn/v1.0.0.html
- src/test/java/uk/nhs/tis/trainee/notifications/event/LtftListenerIntegrationTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/event/LtftListenerTest.java
- src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
- src/test/resources/email/ltft-withdrawn-full-email-contacts.html
- src/test/resources/email/ltft-withdrawn-full-url-contacts.html
- src/test/resources/email/ltft-withdrawn-minimal.html
TIS21-6712
TIS21-6962
TIS21-6964
TIS21-6985
> feat: LTFT withdrawn notification to Trainee

- .aws/task-definition-template.json
> chore: add outbox queue to task def
