Health-Education-England/tis-trainee-notifications

.aws/task-definition-template.json
512mb is not enough to start the service, assigned 1GB of memory to the ECS task.
TIS21-5056
TIS21-5055
=> build: give task 1GB of memory

build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/config/ApplicationConfiguration.java, src/test/java/uk/nhs/tis/trainee/notifications/config/ApplicationConfigurationTest.java
The ECS metadata configuration requires a RestTemplate bean which is not current configured.
Add ApplicationConfiguration with a RestTemplate bean.
TIS21-5056
TIS21-5055
=> fix: configure rest template

.aws/task-definition-template.json, README.md, build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/dto/ProgrammeMembershipEvent.java, src/main/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListener.java, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/resources/application.yml, src/main/resources/templates/email/coj-confirmation.html, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java, src/test/resources/application-test.yml
When a COJ is received an event will be emitted containing the details of the programme membership and signed COJ.
Listen for COJ received events and send a personalised email to notification the user that their COJ was received.
The email should address `Dr <Surname>` when possible, otherwise `Dear Doctor` should be used.
If available, the LO and received date should be included in the email. A link should be provided to give easy access to TSS for download of PDF copies - it is not possible to route them directly to the COJ view due to application state, so they will be sent to the programmes tab instead.
TIS21-5058
TIS21-5055
=> feat: send templated email when COJ received

.aws/task-definition-template.json, README.md, build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/config/CacheConfiguration.java, src/main/java/uk/nhs/tis/trainee/notifications/config/CognitoConfiguration.java, src/main/java/uk/nhs/tis/trainee/notifications/dto/UserAccountDetails.java, src/main/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListener.java, src/main/java/uk/nhs/tis/trainee/notifications/service/UserAccountService.java, src/main/resources/application.yml, src/test/java/uk/nhs/tis/trainee/notifications/config/CacheConfigurationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/config/CognitoConfigurationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceTest.java, src/test/resources/application-redis.yml, src/test/resources/application-test.yml, src/test/resources/bootstrap.properties
Create a UserAccountService which will provide methods for retrieving the user account ID and details for a given TIS person/trainee ID. As the person ID is stored in a custom attribute, the results will be cached for 24 hours due to the inability to filter by custom attributes when querying Cognito.
Update the COJ event handling to retrive the trainee's email and name to use for the email messaging.
TIS21-5058
TIS21-5055
=> feat: get user details from Cognito account

build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListener.java, src/main/resources/templates/email/coj-confirmation.html
The `host` property was renamed to `domain` but the email template was not updated.
Update `coj-confirmation.html` to use `domain` instead of `host`, this will allow emails to include a link to TSS again.
TIS21-5058
TIS21-5055
=> fix: COJ confirmation's link to TSS not working

build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListener.java, src/main/resources/templates/email/coj-confirmation.html, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java, src/test/resources/application-test.yml
The Conditions of Joining notification is not correctly formatted in all cases. If the `syncedAt` timestamp is not available there is an additional space before the period of the event detail.
> We want to inform you that your local deanery office has received you
> signed conditions of joining .
Another issue was the managing deanery and name appearing incorrectly when empty strings rather than `null` values.
e.g.
> Dear Dr ,
> We want to inform you that your local deanery office () has received
your signed Conditions of Joining.
Update the COJ notification template to ensure that whitespace is used correct and more variables handle empty inputs as well as null.
Refactor ConditionsOfJoiningListener to just provide the family name to the template instead of pre-transforming it.
Write …
=> fix: COJ notification formatting

build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListener.java, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/resources/templates/email/coj-confirmation.html, src/main/resources/templates/fragments/greeting.html, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java
The ConditionsOfJoiningListener performs user account lookup and localisation, which should be moved to the EmailService so the behaviour is shared by other sent emails.
Refactor the implementation and tests to move this behaviour.
Refactor the coj-confirmation.html to extract the greeting in to a new greeting.html fragment, which can be shared across templates.
TIS21-5115
TIS21-5134
=> refactor: move common functionality from listener to service

build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/service/UserAccountService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceTest.java
When no account is found for a given trainee ID `null` is being passed back, causing downstream NullPointerExceptions. The UserAccountService should instead return an empty set.
TIS21-5115
=> fix: NPE when no account found

build.gradle, src/main/resources/templates/email/coj-confirmation.html, src/main/resources/templates/email/form-updated.html, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/FormListenerIntegrationTest.java
This is a pretty dumb PR, but without knowing how often the survey URL might be updated/changed, it seemed a waste to engineer it any more abstractly.
Note: as per ticket, no credentials survey at this point. I'm guessing we'll iterate on this before the credentials work goes live anyhow.
TIS21-5184
TIS21-5185
=> feat: survey links

build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/api/HistoryResource.java, src/main/java/uk/nhs/tis/trainee/notifications/dto/HistoryDto.java, src/main/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapper.java, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/test/java/uk/nhs/tis/trainee/notifications/api/HistoryResourceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceIntegrationTest.java, src/test/resources/application-mongodb.yml, src/test/resources/bootstrap.properties
Create an endpoint at `/api/history/{id}` to allow the notification history to be requested for a given trainee ID.
The resulting array will be ordered by descending `sentAt` timestamp (most recent appearing first).
TIS21-5124
TIS21-5125
=> feat: trainee history endpoint

.github/workflows/ci-cd.yml, .github/workflows/pr-analysis.yml
Java 21 is not available during the workflow as the default is 17, Java 21 needs to be passed to the workflow to allow the build to complete.
Gradle 8.4 supports building FOR Java 21, but not running WITH Java 21. So we must also make Java 17 available in the workflow.
The last provided version will be used by default, so `21, 17` is the preferred order to ensure that Gradle gets a compatible version to build with.
TIS21-5124
=> build: set workflow Java versions

.aws/task-definition-template.json, build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/dto/RecordDto.java, src/main/java/uk/nhs/tis/trainee/notifications/event/ProgrammeMembershipListener.java, src/main/java/uk/nhs/tis/trainee/notifications/mapper/ProgrammeMembershipMapper.java, src/main/java/uk/nhs/tis/trainee/notifications/model/Curriculum.java, src/main/java/uk/nhs/tis/trainee/notifications/model/ProgrammeMembership.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ProgrammeMembershipListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/mapper/ProgrammeMembershipMapperTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
The PM updates arrive as a different DTO from the COJ-signed type events. Ignore the latter (which were being processed), and handle the former.
Also: bumped up memory and CPU to stabilise service.
TIS21-5154
=> fix: handle correct PM event data

build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/model/Curriculum.java, src/test/java/uk/nhs/tis/trainee/notifications/mapper/ProgrammeMembershipMapperTest.java
As per errors:
```
2023-11-09T14:34:52.184+00:00 | Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "curriculumTisId" (class uk.nhs.tis.trainee.notifications.model.Curriculum), not marked as ignorable (2 known properties: "curriculumSpecialty", "curriculumSubType"]) | awslogs-tis-trainee-notifications/tis-trainee-notifications/0173351ca7d3429582e8365d9c8ccab6
-- | -- | --
  | 2023-11-09T14:34:52.184+00:00 | at [Source: (String)"[{"curriculumTisId":"98","curriculumName":"General Practice","curriculumSubType":"MEDICAL_CURRICULUM","curriculumSpecialty":"General Practice",
```
=> fix: ignore unmapped curriculum properties

build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
They are cluttering up the logs with errors.
NO-TICKET
=> fix: ignore old History records without tisReference

.aws/task-definition-template.json, build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/dto/EmailEvent.java, src/main/java/uk/nhs/tis/trainee/notifications/event/EmailListener.java, src/main/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapper.java, src/main/java/uk/nhs/tis/trainee/notifications/migration/PopulateNotificationHistoryStatus.java, src/main/java/uk/nhs/tis/trainee/notifications/model/History.java, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationStatus.java, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/resources/application.yml, src/test/java/uk/nhs/tis/trainee/notifications/api/HistoryResourceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/EmailListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/PopulateNotificationHistoryStatusIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceIntegrationTest.java, src/test/resources/application-test.yml
When an email bounces or a complaint if received an event is emitted by SES which ends up on the email failure queue.
Create an event listener, which consumes messages from this queue and updates the stored history to reflect the failure status.
Create a migrator to append a status of `SENT` to all previous notification history documents. This is most likely false, as some of these emails will have failed. However, without additional data this is the best assumption we can make.
TIS21-5445
TIS21-5426
=> feat: update history when emails fail

build.gradle, src/main/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListener.java, src/main/java/uk/nhs/tis/trainee/notifications/event/CredentialListener.java, src/main/java/uk/nhs/tis/trainee/notifications/event/FormListener.java, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/CredentialListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/CredentialListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/FormListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/FormListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java
Not used by the CoJ, Credential or Form listeners at this point, but will be needed to port the current temporary custom history logging for programme notifications into the EmailService. The TisReferenceInfo is needed to determine what notifications have already been sent to a trainee.
Temporary custom history logging code is here: https://github.com/Health-Education-England/tis-trainee-notifications/blob/317d520bf3bdcba3ae0858ba39396ef120360e30/src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java#L154
Use of this data is here: https://github.com/Health-Education-England/tis-trainee-notifications/blob/317d520bf3bdcba3ae0858ba39396ef120360e30/src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java#L126
TIS21-5389
=> feat: include TisReferenceInfo in History

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java
Context:
https://hee-nhs-tis.slack.com/archives/C03G3UK3U82/p1708525663884759
I think we need to rerun the DeleteUnusedPmUpdateHistory migration as well to strip out the junk. Not sure if we can hack that by simply removing it from the mongockChangeLog, or if we should create another copy of that migration?
NO-TICKET
=> fix: do not save notification history for unsent email

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/api/TraineeHistoryResource.java, src/main/java/uk/nhs/tis/trainee/notifications/dto/HistoryDto.java, src/main/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapper.java, src/main/java/uk/nhs/tis/trainee/notifications/model/History.java, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationStatus.java, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/InAppService.java, src/test/java/uk/nhs/tis/trainee/notifications/api/HistoryResourceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/api/TraineeHistoryResourceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapperTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/PopulateNotificationHistoryStatusIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/InAppServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
Trainees should be able to update their notification status to mark in-app notifications as read, unread or archived.
This should be implemented as individual endpoints so that they are restricted on what the status can be set to and removing the possibility of modifying any other fields.
When the notification is marked as read, a new `readAt` field should record the timestamp. Other status changes will not modify that field further and will not be separately recorded. Only the initial reading of the notification matters for data purposes.
TIS21-5682
TIS21-5686
=> feat: allow trainees to update notification status

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/InAppService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/InAppServiceTest.java
The status detail is left blank is several scenarios, however it is currently set to an empty string but should be set to null.
TIS21-5682
=> fix: null status details instead of empty string

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/main/resources/templates/email/placement-updated-week-12/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java
For some reason, there are a lot of past placements being edited, which are triggering issues with AWS too-many-requests since they are all scheduled very close together.
Ignore these, and a few other minor tweaks
NO-TICKET
=> fix: ignore past placements

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/migration/DeleteUnusedPlacementUpdateHistory.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/DeleteUnusedPlacementUpdateHistoryTest.java
The notifications service is thrashing on preprod when trying to redeploy. This should help - if not, I'll give it more resources.
NO-TICKET
=> fix: delete quartz queue of old placement notifications

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapper.java, src/test/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapperTest.java
The front-end _should_ only use the IN_APP notifications, for which the `subjectText` will always be defined, but there is a discussion needed when the FE specialists are back in the office to clarify how they would like the API to support this usage 😁.
At the moment the FE is pulling the whole notification history and then falling-over as the `subjectText` for other types of notification is (currently) null.
To be honest, the way we provide subject text currently is an acknowledged hack - so even though null is probably more technically correct, being picky about the difference is probably not so important right now. The whole area of functionality will probably be refactored soon to better integrate it with the thymeleaf template content.
NO-TICKET
=> fix: default empty-string for undefined subjectText

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapper.java, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/test/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapperTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java
The subject text is not populated on the eportfolio in-app notification DTO because the behaviour is hardcoded. Refactor to retrieve the subject line from the associated template's subject.
TIS21-5615
=> fix: eportfolio subject text population

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/model/Curriculum.java, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/main/resources/application.yml, src/main/resources/templates/in-app/indemnity-insurance/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/mapper/ProgrammeMembershipMapperTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
The indemnity insurance notification should be sent to all new starters taking part in the notification pilot.
There is a conditional section that should be shown dependant on the specialty being in a block indemnity scheme.
Update the Curriculum to include `curriculumSpecialtyBlockIndemnity`. When a qualifying PM is detected, check all associated curricula for any in a block indemnity scheme. When found then show the conditional notification section.
TIS21-5617
TIS21-5837
=> feat: create indemnity insurance notification

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
They are not ever sent, they clutter up the schedule and the logs, and removing them will simplify the PM creation email.
The first in a series of PRs to implement the programme creation email.
TIS21-5038
=> fix: disable programme membership update notifications

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/mapper/PlacementMapper.java, src/main/java/uk/nhs/tis/trainee/notifications/model/Placement.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/main/resources/templates/email/placement-updated-week-12/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
=> fix: refine placement confirm notification

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/main/resources/application.yml, src/main/resources/templates/in-app/less-than-full-time/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
Create an in-app notification for LFTF when a PM is created. The target user must be both a new starter and be part of the notifications pilot.
The contact details should be added to the standard template variables.
TIS21-5613
TIS21-5765
=> feat: in-app ltft notification

build.gradle.kts, src/main/resources/templates/in-app/less-than-full-time/v1.0.0.html
The wording just prior to the contact link in the LTFT notification is awkwardly worded and doesn't read well when the contact is not available.
Fix the template the better handle each scenario.
TIS21-5613
TIS21-5765
=> fix: LTFT contact link wording

build.gradle.kts, src/main/resources/templates/email/placement-updated-week-12/v1.0.0.html
- Capitalise default LO on email title
- rearrange sentence of `placement within a your local deanery office programme` to `placement within a programme of your local deanery office`
- add missing full stop
- Use `<br/>` instead of `<p>` to avoid duplicate display of TSS link when isRegistered is true
Example of Placement notification email:
Another example with GMC number, local office and registered account missing:
=> fix: email content for placement confirm notification

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java
To avoid cluttering-up Sentry with unneeded exceptions, e.g. https://hee-nhs-tis.slack.com/archives/GQ03M1PKN/p1713953281565079 which was triggered by this trainee https://build.tis.nhs.uk/metabase/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjozNiwidHlwZSI6InF1ZXJ5IiwicXVlcnkiOnsic291cmNlLXRhYmxlIjoxNzQyLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDI2NDI1LG51bGxdLCIzMjY4NTEiXV19fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319
Trainees with null email addresses can't receive emails anyway, but better to handle the exception more gracefully.
NO-TICKET
=> fix: handle null email addresses in hashing

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/UserAccountService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceTest.java
When a trainee ID is not found in the existing cache, a lookup is performed on the Cognito user pool and all users are re-cached. As there can be a large number of person records without Cognito accounts it can lead to attempts to constant re-cache the user pool over and over.
A fifteen minute window should be added after each full cache operation, during which no re-caching will occur. This will help reduce demand on the Cognito API when processing large numbers of contact detail changes. The fifteen minutes is fairly arbitrary and may need tweaking, until a longer term solution can be put in place.
TIS21-5904
=> fix: repeated caching of missing users

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
We only need to send notifications for future PMs and Placements, so exclude any with a past start date (Current and Past).
TIS21-5967
TIS21-5970
=> fix: ignore non-future PMs and Placements

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
=> fix: handle nulls when determining excluded PMs

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
The trainee profile was not explicitly trusted and is only used when no Cognito account was found based on the trainee ID. The Cognito looking is done using an expensive caching operation as there is no direct way to query based on tranine ID.
Now that the Cognito account and trainee profile emails are kept in sync it is preferred to lookup the Cognito account based on the email from the trainee profile.
Update the NotificationService to retrieve the trainee profile first, then perform a single Cognito query to find an existing account for the email address.
There is a small edge case where the Cognito account could not be updated in time either due to either race conditions or issues like multiple accounts (in which case the UM service errors), in those cases the email will be sent based …
=> feat: send to profile email address

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
As the user account is looked up by email/username there are no longer multiple failure scenarios (e.g. duplicate accounts) that need be wrapped in a generic IllegalArgumentException.
The UserNotFoundException is passed through, so catch it and return `null` back to the NotificationService so it can continue to merge the user details.
TIS21-5967
=> fix: catch UserNotFoundException

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/dto/UserDetails.java, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/test/java/uk/nhs/tis/trainee/notifications/config/MongoConfigurationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/CredentialListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/CredentialListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/FormListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/FormListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/PlacementListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/DeleteUnusedPlacementUpdateHistoryTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/DeleteUnusedPmUpdateHistoryTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/InAppServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/TemplateServiceTest.java
Currently when an email is missing the sending causes an error and the
triggering message ends up on the DLQ. This means that Local Offices are
unable to report on these particular types of failure easily.
Update the NotificationService and EmailService to handle `null` or
empty values for the email field on the trainee record.
If the email is `null` or empty then no attempt should be made to find
the associated user account.
TIS21-5984
TIS21-5985
=> feat: store failure when email missing

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/ContactDetailsService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ContactDetailsServiceTest.java
When an email address is not available during sending, the failure is recorded with no email address.
Upon receiving an updating set of contact details the previously failed message should be resent.
Update the ContactDetailsService to properly handle the `null` value is when determining whether to resend the message or not.
TIS21-5984
=> fix: resending failures when previous contact null

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java
When a template variable value is null the resending will fail due to `Map.copyOf()` not supporting null values.
Update the EmailService to create a new instance of the map without using that function call.
NO-TICKET
=> fix: handle resending template with null vars

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/main/resources/application.yml, src/main/resources/templates/in-app/non-employment/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java
I have followed the ticket to name the notification subject as `Placement Confirmation Does Not Constitute An Offer Of Employment` and the key name as `NON_EMPLOYMENT`, please free feel to advise if you think of any better names.
TIS21-5563
TIS21-5845
=> feat: placement not employment in-app notification

.aws/task-definition-template.json, build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/dto/AccountUpdatedEvent.java, src/main/java/uk/nhs/tis/trainee/notifications/event/UserAccountListener.java, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java, src/main/resources/application.yml, src/main/resources/templates/email/email-updated-new/v1.0.0.html, src/main/resources/templates/email/email-updated-old/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/event/UserAccountListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java
When a user account email is changed, the trainee should receive an email to both the new and old email addresses to inform them of the change to their contact and sign-in details.
Update the UserAccountListener to receive account update events and use the EmailService to send both emails.
TIS21-6006
TIS21-6009
TIS21-6010
=> feat: notify trainees of email changes

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/main/resources/templates/in-app/placement-useful-information/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java
the template name was too long to fit within the bounds of the notification when displayed on the FE, name has been shortened from PLACEMENT_USEFUL_INFORMATION to USEFUL_INFORMATION & update a link in the template to open in a new tab instead of navigating away from TSS
NOT_TICKET
=> refactor: shorten template name to fit formatting

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/event/PlacementListener.java, src/main/resources/application.yml
Configure quartz for clusting, setting `instanceId=AUTO` allows Quartz to generate unique instance IDs.
NO-TICKET
=> fix: quartz clustering

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
And some refactoring of programme membership service tests.
To make it easier to review,
https://github.com/Health-Education-England/tis-trainee-notifications/pull/167 is being split up. This is the first part.
And here is the second part: https://github.com/Health-Education-England/tis-trainee-notifications/pull/170
TIS21-5991
=> feat: new getAllHistoryForTrainee method

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/event/UserAccountListener.java, src/main/java/uk/nhs/tis/trainee/notifications/model/ProgrammeMembership.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/main/resources/templates/email/placement-updated-week-12/v1.0.0.html, src/main/resources/templates/email/programme-created/v1.0.0.html, src/main/resources/templates/in-app/deferral/v1.0.0.html, src/main/resources/templates/in-app/less-than-full-time/v1.0.0.html, src/main/resources/templates/in-app/non-employment/v1.0.0.html, src/main/resources/templates/in-app/placement-information/v1.0.0.html, src/main/resources/templates/in-app/placement-useful-information/v1.0.0.html, src/main/resources/templates/in-app/sponsorship/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
Adding meaningful subject to the "mailto" link.
**Programme notifications:**
eg. Normal subject text - GMC: 1234567, Prog No: ABC1234
**Placement notifications:**
eg. Normal subject text - GMC: 1234567, Start Date: 00/00/0000
**If the data is missing, it will appear as "unknown":**
eg. Normal subject text - GMC: unknown, Start Date: unknown
TIS21-5893
TIS21-5930
TIS21-5931
TIS21-5932
=> fix: meaningful subject for mailto link

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/config/MongoCollectionConfiguration.java, src/main/java/uk/nhs/tis/trainee/notifications/config/MongoConfiguration.java, src/test/java/uk/nhs/tis/trainee/notifications/TisTraineeNotificationsApplicationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/config/DateToObjectConverterTest.java, src/test/java/uk/nhs/tis/trainee/notifications/config/MongoCollectionConfigurationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/config/MongoConfigurationIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/config/MongoConfigurationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/repository/FlywayMigrationsTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceIntegrationTest.java
...if the target field is an Object.
This feels like it exposes us to unintended consequences if a true Date is held in the template variables, when it would be converted to a LocalDate, so I'm not sure if it really resolves the original 'gotcha' :/
NO-TICKET
=> fix: read mongo Dates as LocalDates

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/event/UserAccountListener.java, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/UserAccountService.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/CredentialListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/FormListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/UserAccountListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceTest.java
Cognito is charged based on monthly active users, this is usually a fairly low number and within free limits. However, it was found that the usage of `AdminGetUser` causes the requested account to be marked as active for that month.
After reloading all placement/PM data to trigger notification generation, that resulted in 66k active users. Most of which were not actually active.
Update the UserAccountService to use a filtered `listUsers` request instead of the `AdminGetUser` request. The only difference between the results is some minor structure changes and some MFA attributes not being included in `listUsers`. For our case both of these differences are acceptable.
The `sub` and `email` are both unique, so there is no need to handle multiple results.
TIS21-6103
TIS21-6104
=> fix: get user details without increasing MAU

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/UserAccountService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceTest.java
As per error
2024-05-31T09:27:39.382Z	Caused by:
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex at java.base/java.util.ArrayList.get(Unknown Source) at java.base/java.util.Collections$UnmodifiableList.get(Unknown Source) uk.nhs.tis.trainee.notifications.service.UserAccountService.getUserDetails(UserAccountService.java:170)
and guidance on the hasUsers() method: "For responses, this returns true if the service returned a value for the Users property. This DOES NOT check that the value is non-empty (for which, you should check the isEmpty() method on the property)."
NO-TICKET
=> fix: handle empty user collection

.aws/task-definition-template.json, README.md, build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/config/EventNotificationProperties.java, src/main/java/uk/nhs/tis/trainee/notifications/config/ObjectIdSerializerModule.java, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationStatus.java, src/main/java/uk/nhs/tis/trainee/notifications/service/EventBroadcastService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/main/resources/application.yml, src/test/java/uk/nhs/tis/trainee/notifications/service/EventBroadcastServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java
Note: at present History deletes are 'faked' by broadcasting a dummy record with NotificationStatus=DELETED (the actual records are deleted from the local repository)
TIS21-6085
=> feat: broadcast notification events

.aws/task-definition-template.json, build.gradle.kts
Currently won't start with ' invalid ssm parameters: tis-trainee-preprod-notifications-event'.
NO-TICKET
=> fix: bad SSM parameter for SNS

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java
Some in-app Histories are created with null id, leading to messages in the ndw notification event queue like
`{"id": null, ....}` which will cause problems since the id is used for the filename. Using the saved object means the id will be populated.
NO-TICKET
=> fix: broadcast saved History (with non-null id)

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/event/PlacementListener.java, src/main/java/uk/nhs/tis/trainee/notifications/event/ProgrammeMembershipListener.java, src/main/java/uk/nhs/tis/trainee/notifications/mapper/HistoryMapper.java, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationStatus.java, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/tis/trainee/notifications/event/PlacementListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ProgrammeMembershipListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
In-App Notifications:
- Return future In-App notifications with SCHEDULED status
(For In-App notifications, only return SCHEDULED status in DTO but not storing in DB)
Email Notifications:
- Save tisReference, recipient, template variables and everything the template needed of the scheduled Emails to the database with status SCHEDULED
- Currently non-pilot will also be scheduled in the Quartz, they will be excluded just before it is sent out. I have keep this unchanged in Quartz, but only save notifications of New starter in Pilot with correct notification type to History DB, so only the actionable notification will be shown on TIS Notification tab.
- Update scheduled history in DB when it is sent
Sample of SCHEDULED email in History collection.
TIS21-6014
TIS21-6077
TIS21-6076
=> Feat/handle SCHEDULED status of notifications

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
The `isValidGmc` flag is not being set, resulting the template including both the GMC number and a message that the GMC number is invalid/not available.
Calculate and include the GMC number validity when enriching the job details.
TIS21-6449
=> fix: set `isValidGmc` flag

build.gradle.kts, src/main/resources/application.yml, src/main/resources/templates/in-app/day-one/v1.1.0.html
Contents update in Day One In-App notification
When designated body is missing
TIS21-6503
TIS21-6539
=> feat: update In-App Day One notifications wording (v1.1.0)

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationEvent.java, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java
On staging observed:
1. It would be sent if the original faulty placement notification was failed / scheduled
2. It would be sent more than once.
TIS21-6650
=> fix: do not send rollout correction incorrectly

build.gradle.kts, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java
The previous PR threw-up when deploying to staging.
NO-TICKET
=> fix: time-sensitive test robustified

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/dto/CojPublishedEvent.java, src/main/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListener.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ConditionsOfJoiningListenerTest.java
A check is made to determine whether to skip sending a Conditions of Joining confirmation, however it is not checking that the confirmation was for the same PM.
As a result, currently no confirmation can be sent if the user has ever previously recieved one.
Update the ConditionsOfJoiningListener to store a reference to the PM alongside the confirmation history, that reference should then be checked against incoming events to filter out duplications without excluding new and different PMs.
TIS21-6106
TIS21-6663
=> fix: only skip COJ if previous sent for same PM

build.gradle.kts, src/main/resources/application-local.yml
Create `application-local.yml` with opinionated defaults to allow the service to be started without any additional configuration and custom environmental variables.
There is still an expectation that Localstack resources will be created upfront as referred to in the properties file.
Bump Spring Boot patch version to resolve an issue with generating docker images on 3.3.0
NO-TICKET
=> chore: create local profile properties

.aws/task-definition-template.json, build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/event/GmcListener.java, src/main/java/uk/nhs/tis/trainee/notifications/model/GmcRejectedEvent.java, src/main/java/uk/nhs/tis/trainee/notifications/model/NotificationType.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/resources/application.yml, src/main/resources/templates/email/gmc-rejected-lo/v1.0.0.html, src/main/resources/templates/email/gmc-rejected-trainee/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/event/GmcListenerTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/EmailServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java
This is slight rework of the reverted https://github.com/Health-Education-England/tis-trainee-notifications/pull/235 . In particular, the trainee- and LO- emails have been separated into distinct templates instead of using the same template with a 'cc' fragment included in the trainee copy. This necessitated a slight rework of GmcListener and NotificationService code.
Updated email contents:
To trainee:
To LO:
TIS21-6638
=> Feat: handle GMC-update rejection

build.gradle.kts, settings.gradle.kts
Migrate to version `0.0.3` of the trainee version catalog. This change will incorporate the following dependency changes:
- Spring Boot (plugin) `3.3.6` to `3.3.8`
- Spring Dependency Management (plugin) `1.1.4` to `1.1.7`
- Spring Cloud (BOM) `2023.0.0` to `2023.0.5`
- Spring Cloud AWS (BOM) `3.1.0` to `3.1.1`
- AWS X-Ray `2.15.1` to `2.15.3`
The `com.playtika.testcontainers` dependencies are not included in the version catalog as they should be replaced to take advantage of the improved Spring support for test containers.
NO-TICKET
=> chore(deps): migrate to trainee version catalog

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/event/ProgrammeMembershipListener.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/tis/trainee/notifications/event/ProgrammeMembershipListenerTest.java
Events arrive like
```
2025-04-03T07:56:33.083Z  INFO 1 --- [ntContainer#9-1] u.n.t.t.n.e.ProgrammeMembershipListener  : Handling programme membership delete event ProgrammeMembershipEvent[tisId=c73fbd6c-62a8-405e-9092-0fd245f4e1df, recrd=RecordDto(data={uuid=c73fbd6c-62a8-405e-9092-0fd245f4e1df, programmeMembershipType=SUBSTANTIVE, programmeStartDate=2025-08-06, programmeEndDate=2027-08-03, programmeId=18500, personId=334298, trainingPathway=N/A, amendedDate=2025-03-11T14:30:17.249Z}, metadata={timestamp=2025-04-03T07:56:27.659948Z, record-type=data, operation=delete, partition-key-type=schema-table, schema-name=tcs, table-name=ProgrammeMembership, transaction-id=30700426879410})].
```
but the existing code would not have deleted them from the DB because the personId was not set …
=> fix: actually delete scheduled PM notifications on PM delete

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/EmailService.java, src/main/resources/application-local.yml
The exceptions throw when looking for a user account and getting zero or multiple results are generic and static.
Update EmailService to throw a more dynamic exception message, including the trainee ID, found account IDs and found account count, so that diagnosing is easier without trawling through logs for context from earlier log messages.
NO-TICKET
=> refactor: improve account != 1 errors

build.gradle.kts, src/main/resources/application.yml, src/main/resources/templates/email/ltft-approved-tpd/v1.0.1.html, src/main/resources/templates/email/ltft-approved/v1.0.1.html, src/main/resources/templates/email/ltft-submitted-tpd/v1.0.1.html, src/main/resources/templates/fragments/ltft-summary/v1.0.0.html, src/test/java/uk/nhs/tis/trainee/notifications/event/LtftListenerIntegrationTest.java, src/test/resources/email/ltft-approved-full-email-contacts.html, src/test/resources/email/ltft-approved-full-url-contacts.html, src/test/resources/email/ltft-approved-minimal.html, src/test/resources/email/ltft-approved-tpd-full-email-contacts.html, src/test/resources/email/ltft-approved-tpd-full-url-contacts.html, src/test/resources/email/ltft-submitted-tpd-full-email-contacts.html, src/test/resources/email/ltft-submitted-tpd-full-url-contacts.html, src/test/resources/email/ltft-submitted-tpd-minimal.html
the 
1. LTFT approved, 
2. LTFT approved TPD and 
3. LTFT submitted TPD 
emails all include a summary of the LTFT application. These are in tabular form, except for (3).
Fields included:
Programme name, CCT start date, anticipated end date (CCT date), current WTE, new WTE
(2) omits the anticipated end date, and 
(3) omits the anticipated end date and includes the programme start date
I would suggest 
* making them all tabular
* adding anticipated end date to (2)
* adding anticipated end date to (3) <--- is it ok to remove programme start date here?
This is what is implemented in this PR.
How does that sound?
TIS21-7246
=> fix: standardise LTFT summary in email templates

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/PlacementService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/PlacementServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/ProgrammeMembershipServiceTest.java
A notification window exists which spreads notification scheduling out over 9 hours to try and avoid rate limits accessing the Cognito API. However, we are now seeing delivery failures to gmail accounts as a result of Google blocking our sudden surge in emails sent to them.
Increase the notification window to 24 hours in an attempt to smooth the surges and avoid the automated blocking.
A longer term fix remains to buffer scheduled emails in to a queue, which can then be dynamically delayed/retried more easily based on these sorts of bounces.
TIS21-7290
=> fix: bump notifications window to 24 hours

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/migration/ResendGoogleMailFailures.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/ResendGoogleMailFailuresIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/ResendGoogleMailFailuresTest.java
Google Mail blocked the majority of our emails sent to gmail and googlemail addresses due to a sudden spike in sends. This has left 3734 failed emails which need to be retried.
Create a migrator to re-schedule the failed emails, spread over a 24 hour period to hopefully avoid any automated blocks.
TIS21-7290
=> fix: retry blocked email notifications

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/migration/ResendGoogleMailFailures.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/ResendGoogleMailFailuresTest.java
The resend migration is deleting notifications when it could not be rescheduled, update the migrator to skip the deletion step so the original failure is retained and no notifications are lost.
TIS21-7290
=> fix: keep notifications when resend fails

src/main/java/uk/nhs/tis/trainee/notifications/migration/ResendGoogleMailFailures.java
The google resend migrator is restarting due to some runtime exceptions that weren't accounted for.
Catch a generic Exception instead of only the checked exxceptions.
TIS21-7290
=> fix: catch all exceptions

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/dto/LtftUpdateEvent.java, src/main/java/uk/nhs/tis/trainee/notifications/event/LtftListener.java, src/main/java/uk/nhs/tis/trainee/notifications/model/TisReferenceType.java, src/test/java/uk/nhs/tis/trainee/notifications/event/LtftListenerTest.java
tis-trainee-forms includes the id in the published DTO when the form is e.g. submitted (here: https://github.com/Health-Education-England/tis-trainee-forms/blob/91e7fdbb4bccd0c6f5a54acff520db9ed3a8a5fe/src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftFormDto.java#L59) 
With this PR, the History that the notification service broadcasts when the email status changes from PENDING->SENT/FAILED will include TisReferenceInfo with this form ID, so that the forms service can in turn find the correct form to update with the new email status.
TIS21-7025
=> feat: add TisReferenceInfo to LTFT history

.aws/task-definition-template.json, build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/event/EmailListener.java, src/main/java/uk/nhs/tis/trainee/notifications/migration/ResendAugust2025RotationScheduleFailures.java, src/main/java/uk/nhs/tis/trainee/notifications/service/MessageSendingService.java, src/main/java/uk/nhs/tis/trainee/notifications/service/NotificationService.java, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/java/uk/nhs/tis/trainee/notifications/TisTraineeNotificationsApplicationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/config/MongoConfigurationIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/matcher/DateCloseTo.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/DeleteOrphanScheduledHistoryTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/PopulateNotificationHistoryStatusIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/ResendAugust2025RotationScheduleFailuresIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/ResendAugust2025RotationScheduleFailuresTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/ResendGoogleMailFailuresIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/ResetLtftSubmittedTraineeHistoryTest.java, src/test/java/uk/nhs/tis/trainee/notifications/migration/UpdateInAppTvTest.java, src/test/java/uk/nhs/tis/trainee/notifications/repository/FlywayMigrationsTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/MessageSendingServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/NotificationServiceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/UserAccountServiceIntegrationTest.java, src/test/resources/application-test.yml
Currently messages are sent instantly if either they qualify for non-scheduled sending (e.g. form confirmations) or a schedule was triggered.
Non-scheduled messages are generally sourced from a queue, so have retry available. But scheduled messages are not rescheduled on failure, so if the message is not sent the trigger is removed and never fires again. This results in "lost" messages which remain as "scheduled" in the database but are not scheduled in Quartz for sending.
Scheduled messages should be buffered in an "outbox" consisting of a message queue, which is read back in by this service. This allows the rate of sending to be throttled, retries to be applied more consistently and generally better monitoring and alerting to issues.
Existing failures will still need a separate migrator …
=> feat: queue emails in an outbox queue before send

build.gradle.kts, src/main/java/uk/nhs/tis/trainee/notifications/api/HistoryResource.java, src/main/java/uk/nhs/tis/trainee/notifications/model/History.java, src/main/java/uk/nhs/tis/trainee/notifications/service/HistoryService.java, src/test/java/uk/nhs/tis/trainee/notifications/api/HistoryResourceTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceIntegrationTest.java, src/test/java/uk/nhs/tis/trainee/notifications/service/HistoryServiceTest.java
(assumed 'yes'):
```
Do we update the following Notification History field:
recipient.id
And leave these unchanged?
recipient.contact (email address)
template.variables.personId
template.variables.email
template.variables.hashedEmail
```
(assumed 'update all'):
`If the status != SENT or FAILED do we update them, or delete them (since presumably they are obsolete?)`
Downstream service effects: 
Published to tis-trainee_env}-notification-event SNS and picked up by 
* tis-trainee-forms-{env}-notification-event, but ignored as no change to the tpdEmailValidity
* tis-trainee-ndw-{env}-notification-event and updated data published to NDW
TIS21-7635
=> feat: endpoint to move history to new trainee
